import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';

export type IpLogDocument = HydratedDocument<IpLog>;

/**
 * Main IP log schema - stores all requests
 * Optimized for MongoDB Atlas + Vercel deployment
 */
@Schema({
  timestamps: true, // Auto-creates createdAt and updatedAt
  collection: 'ip_logs',
})
export class IpLog {
  // Hashed IP for privacy (GDPR compliant)
  @Prop({ index: true })
  hashedIp?: string;

  // Raw IP (opt-in only, use with caution)
  @Prop()
  rawIp?: string;

  @Prop()
  userAgent?: string;

  @Prop()
  method?: string;

  // Full request path
  @Prop({ index: true })
  path?: string;

  // Auto-generated by timestamps: true
  createdAt?: Date;
  updatedAt?: Date;
}

export const IpLogSchema = SchemaFactory.createForClass(IpLog);

// Compound indexes for better query performance
IpLogSchema.index({ path: 1, createdAt: -1 });
IpLogSchema.index({ hashedIp: 1, createdAt: -1 });
