import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';

export type IpResourceLogDocument = HydratedDocument<IpResourceLog>;

/**
 * Resource-specific IP tracking schema
 * Use this for tracking IPs per product, order, article, etc.
 * Optimized for queries like "which IPs viewed/ordered product 123"
 */
@Schema({
  timestamps: true,
  collection: 'ip_resource_logs',
})
export class IpResourceLog {
  // Hashed IP for privacy
  @Prop({ required: true, index: true })
  hashedIp: string;

  // Raw IP (opt-in only)
  @Prop()
  rawIp?: string;

  // Resource type: 'product', 'order', 'article', 'video', etc.
  @Prop({ required: true, index: true })
  resourceType: string;

  // Resource identifier (e.g., product ID, order ID)
  @Prop({ required: true, index: true })
  resourceId: string;

  // Action performed: 'view', 'order', 'download', 'click', etc.
  @Prop({ index: true })
  action?: string;

  @Prop()
  userAgent?: string;

  @Prop()
  method?: string;

  // Full request path for reference
  @Prop()
  path?: string;

  // Additional metadata (flexible JSON storage)
  @Prop({ type: Object })
  metadata?: Record<string, any>;

  // Auto-generated by timestamps: true
  createdAt?: Date;
  updatedAt?: Date;
}

export const IpResourceLogSchema = SchemaFactory.createForClass(IpResourceLog);

// Compound indexes for optimal query performance
IpResourceLogSchema.index({ resourceType: 1, resourceId: 1, createdAt: -1 });
IpResourceLogSchema.index({ resourceType: 1, resourceId: 1, hashedIp: 1 });
IpResourceLogSchema.index({ hashedIp: 1, resourceType: 1, createdAt: -1 });
IpResourceLogSchema.index({ resourceType: 1, action: 1, createdAt: -1 });
