import { Game } from '../types/Game';


export const mockGames: Game[] = [
{
id: '1',
slug: 'nebula-odyssey',
title: 'Nebula Odyssey',
description: 'Pilot your starfighter across procedurally generated galaxies in this rogue-lite space adventure.',
image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1600&auto=format&fit=crop',
genre: 'Action',
price: 29.99,
featured: true,
},
{
id: '2',
slug: 'runic-realms',
title: 'Runic Realms',
description: 'Forge spells, master dungeons, and shape a world driven by your choices.',
image: 'https://images.unsplash.com/photo-1505744386214-51dba16a26fc?q=80&w=1600&auto=format&fit=crop',
genre: 'RPG',
price: 49.99,
featured: true,
},
{
id: '3',
slug: 'tranquil-tracks',
title: 'Tranquil Tracks',
description: 'A cozy sim where you restore a forgotten railway and the towns along its route.',
image: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?q=80&w=1600&auto=format&fit=crop',
genre: 'Simulation',
price: 19.99,
featured: false,
},
{
id: '4',
slug: 'mech-frontier',
title: 'Mech Frontier',
description: 'Tactical mech battles with deep customization and co-op missions.',
image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=1600&auto=format&fit=crop',
genre: 'Strategy',
price: 59.99,
featured: true,
},
{
id: '5',
slug: 'skyline-skater',
title: 'Skyline Skater',
description: 'Flow through a neon city with fluid movement and a synthwave soundtrack.',
image: 'https://images.unsplash.com/photo-1482192505345-5655af888cc4?q=80&w=1600&auto=format&fit=crop',
genre: 'Indie',
price: 14.99,
featured: false,
},
{
id: '6',
slug: 'abyss-watch',
title: 'Abyss Watch',
description: 'Dive into the deep and uncover the secrets of an ancient civilization.',
image: 'https://images.unsplash.com/photo-1504898770365-14faca6a7320?q=80&w=1600&auto=format&fit=crop',
genre: 'Adventure',
price: 39.99,
featured: false,
}
];