import { Injectable } from '@nestjs/common';
import { FinalWriterInterface } from '../interfaces/final-writer.interface';

@Injectable()
export class FinalWriterCode implements FinalWriterInterface {
  async compose(subQuestions: string[], summaries: string[], checks: { contradictions: string[] }): Promise<string> {
    // Merge summaries under subquestions
    let out = '';
    for (let i = 0; i < subQuestions.length; i++) {
      out += `Q: ${subQuestions[i]}\nAnswer: ${summaries[i] || 'No summary available.'}\n\n`;
    }
    if (checks?.contradictions?.length) {
      out += 'Contradictions found:\n';
      checks.contradictions.forEach((c, idx) => (out += `${idx + 1}. ${c}\n`));
    }
    out += '\n(Generated by code-mode merger)';
    return out;
  }
}
